name: policyforgeai
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  file_picker: ^8.1.4
  get_it: ^8.0.2
  injectable: ^2.3.0
  
  # Document Editing
  flutter_quill: ^10.8.5
  diff_match_patch: ^0.4.1
  
  # AI and NLP
  dart_openai: ^5.1.0
  
  # Collaboration
  web_socket_channel: ^3.0.1
  shared_preferences: ^2.2.1
  
  # Utils
  uuid: ^4.5.1
  intl: ^0.19.0
  logger: ^2.0.2
  http: ^1.1.0
  pdf: ^3.10.4
  html: ^0.15.4
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.4.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true
